name: Daily running bot

on: 
  schedule:
    - cron: '0 12 * * *'

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t telegram-bot .

    - name: Run Docker container
      run: |
        docker run telegram-bot
