name: Daily running bot

on: 
  schedule:
    - cron: '0 12 * * *'

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev

    - name: Install Python dependencies
      run: |
        pip install aiogram

    - name: Run script
      run: |
        python telegram_bot.py

